server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

# zuul注册到Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

# 路由映射
zuul:
  ignored-services: "*"
  routes:
    mydept:
      serviceId: microservicecloud-dept
      path: /mydept/**


info:
  app.name: yufeng-microcloud
  company.name: www.yufeng.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
